name=gnl-button
version=2.0.0
author=gnoolson
maintainer=gnoolson@gmail.com
sentence=Button library
paragraph=Button library for Arduino
category=Signal Input/Output
url=https://github.com/gnoolson/gnl-button
architectures=*
